<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZm6VPxQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZm6VPxQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZm6VPxQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZm6VPxQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZm6VPxQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zm6VPxQ',
    'container.build_id' => '2e2406a9',
    'container.build_time' => 1703142728,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZm6VPxQ');
