<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNz23Hpr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNz23Hpr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNz23Hpr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNz23Hpr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNz23Hpr\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nz23Hpr',
    'container.build_id' => '3f48a09b',
    'container.build_time' => 1674321500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNz23Hpr');
